name: Build & Deploy

on:
  push:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  package:
    runs-on: [k8s-internal]
    outputs:
      dockertag: ${{ steps.dockertag.outputs.dockertag }}
    steps:
      - uses: actions/checkout@v2

      - name: Vault Login
        uses: Chia-Network/actions/vault/login@main
        with:
          vault_url: ${{ secrets.VAULT_URL }}
          role_name: github

      - name: Get secrets from vault
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ env.VAULT_TOKEN }}
          secrets: |
            secret/data/backblaze/cat1-download/cat1-download-read applicationKey | BACKBLAZE_APP_KEY;
            secret/data/backblaze/cat1-download/cat1-download-read keyID | BACKBLAZE_KEY_ID;

      - name: Install b2 CLI tool
        run: |
          wget https://github.com/Backblaze/B2_Command_Line_Tool/releases/latest/download/b2-linux
          chmod +x ./b2-linux
          mv ./b2-linux ./b2
          ./b2 --help

      - name: Authenticate to Backblaze
        run: |
          ./b2 authorize-account ${BACKBLAZE_KEY_ID} ${BACKBLAZE_APP_KEY}

      - name: Get CSV snapshot database from Backblaze
        run: |
          ./b2 download_file_by_name cat1-download cat1-snapshot.zip cat1-snapshot.zip
          unzip cat1-snapshot.zip
          mv cat1_csv_files/000_cat1-snapshot.csv cat1-snapshot.csv

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set docker tag to build
        id: dockertag
        run: echo "::set-output name=dockertag::ghcr.io/chia-network/cat1-balance:${{ github.sha }}"

      - name: Build Docker Container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.dockertag.outputs.dockertag }}

  deploy:
    needs:
      - package
    runs-on: [k8s-internal]
    container:
      image: registry.gitlab.com/cmmarslender/kubectl-helm:v3.9.0
    steps:
      - uses: actions/checkout@v2

      - name: Vault Login
        uses: Chia-Network/actions/vault/login@main
        with:
          vault_url: ${{ secrets.VAULT_URL }}
          role_name: github

      - name: Get secrets from vault
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ env.VAULT_TOKEN }}
          secrets: |
            secret/data/fmt/k8s/ghcr_image_pull username | IMAGE_PULL_USERNAME;
            secret/data/fmt/k8s/ghcr_image_pull password | IMAGE_PULL_PASSWORD;
            secret/data/fmt/k8s/fremont-baremetal api_server_url | K8S_API_SERVER_URL;

      - name: Login to k8s cluster
        uses: Chia-Network/actions/vault/k8s-login@main
        with:
          vault_url: ${{ secrets.VAULT_URL }}
          vault_token: ${{ env.VAULT_TOKEN }}
          backend_name: fremont-baremetal
          role_name: github-actions
          cluster_url: ${{ env.K8S_API_SERVER_URL }}

      - uses: Chia-Network/actions/k8s/image-pull-secret@main
        with:
          secret_name: cat1-balance-image-pull
          namespace: cat1-balance
          username: ${{ env.IMAGE_PULL_USERNAME }}
          password: ${{ env.IMAGE_PULL_PASSWORD }}
          docker_server: "ghcr.io"

      - uses: Chia-Network/actions/helm/deploy@main
        env:
          DOCKER_TAG: ${{ needs.package.outputs.dockertag }}
        with:
          namespace: cat1-balance
          app_name: "cat1-balance"
          helm_chart: "./k8s/charts/cat1-balance"
          helm_values: "./k8s/values/prd.yaml"
